alias grep='grep --color=auto'
alias less='less -R'
alias ls='ls --color=auto -ahl'
alias lsd='ls | grep ^d'
alias lsf='ls | grep ^-'
alias lsl='ls | grep ^l'
alias ssv='vagrant ssh'
alias vbox='VBoxManage'
alias vh='vagrant halt'
alias vs='vagrant status'
alias vu='vagrant up'
